export {default as AddPost} from "./AddPost"
export {default as AllPost} from "./AllPost"
export {default as EditPost} from "./EditPost"
export {default as Home} from "./Home"
export {default as Login} from "./Login"
export {default as Post} from "./Post"
export {default as Signup} from "./SignUp"